server:
  instance-id: ${SERVER_INSTANCE_ID:default}

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

app:
  jwt:
    registry:
      type: ${APP_JWT_REGISTRY_TYPE:redis}  # InMemory 대신 Redis 사용
    max-active-count: 3
  messaging:
    type: ${APP_MESSAGING_TYPE:kafka}    # 분산 메시징을 위해 Kafka 사용
  sse:
    type: ${APP_SSE_TYPE:redis}

logging:
  level:
    com.sprint.mission.discodeit: INFO
    org.springframework.kafka: DEBUG
    org.springframework.data.redis: DEBUG
